authors/urls.py
from django.urls import path
from . import views

app_name = 'authors'

urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('register/create/', views.register_create, name='register_create'),
    path('login/', views.login_view, name='login'),
    path('login/create/', views.login_create, name='login_create'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
    path('authors/', include('authors.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

projeto1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

authors/models.py
from django.db import models

# Create your models here.

authors/forms.py
from typing import Any
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

def add_attr(field, attr_name, attr_new_val):
    existing_attr = field.widget.attrs.get(attr_name, '')
    field.widget.attrs[attr_name] = f'{existing_attr} {attr_new_val}'.strip()

def add_placeholder(field, placeholder_val):
    add_attr(field, 'placeholder', placeholder_val)

class RegisterForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        add_placeholder(self.fields['username'], 'Your username')
        add_placeholder(self.fields['email'], 'Your e-mail')
        add_placeholder(self.fields['first_name'], 'Your name')
        add_placeholder(self.fields['last_name'], 'Your surname')
        add_placeholder(self.fields['password'],'Type your password here')
        add_placeholder(self.fields['password2'],'Repeat your password')

    first_name = forms.CharField(
        error_messages={'required': 'Write your first name'},
        label='First name'
    )

    last_name = forms.CharField(
        error_messages={'required': 'Write your last name'},
        label='Last name'
    )

    email = forms.EmailField(
        error_messages={'required': 'E-mail is required'},
        label='E-mail'
    )

    password = forms.CharField(
        required=True,
        label='Password',
        widget=forms.PasswordInput(),
        error_messages={'required': 'Password must not be empty'}
    )

    password2 = forms.CharField(
        required=True,
        label='Password2',
        widget=forms.PasswordInput(),
        error_messages={'required': 'Please, repeat your password'}
    )
    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'username',
            'email',
            'password',
        ]

        labels = {
            'username': 'Username',
            'first_name': 'First name',
            'last_name': 'Last name',
            'email': 'E-mail',
            'password': 'Password',
        }

        def clean_email(self):
            email = self.cleaned_data.get('email', '')
            exists = User.objects.filter(email=email).exists()

            if exists:
                raise ValidationError('User e-mail is already in use', code='invalid')
            
            return email

    def clean(self):
        cleaned_data = super().clean()

        password = cleaned_data.get('password')
        password2 = cleaned_data.get('password2')

        if password != password2:
            password_confirmation_error = ValidationError(
                'Password and password2 must be equal',
                code='invalid'
            )
            raise ValidationError({
                'password': password_confirmation_error,
                'password2': [
                    password_confirmation_error,
                ],
            })
        
class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(
        widget=forms.PasswordInput()
    )

authors/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm, LoginForm
from django.http import Http404
from django.contrib import messages
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from recipes.models import Recipe

def register_view(request):
   register_form_data = request.session.get('register_form_data', None)
   form = RegisterForm(register_form_data)
   return render(request, 'authors/pages/register_view.html', {
      'form': form,
   })

def register_create(request):
   if not request.POST:
      raise Http404()
   
   POST = request.POST
   request.session['register_form_data'] = POST
   form = RegisterForm(POST)

   if form.is_valid():
      user = form.save(commit=False)
      user.set_password(user.password)
      user.save()
      messages.success(request, 'Your user is created, please log in.')
      del(request.session['register_form_data'])
      return redirect(reverse('authors:login'))
   
   return redirect('authors:register')

def login_view(request):
   form = LoginForm()
   return render(request, 'authors/pages/login.html', {
      'form': form,
      'form_action': reverse('authors:login_create')
   })

def login_create(request):
   if not request.POST:
      raise Http404()
   
   form = LoginForm(request.POST)
   login_url = reverse('authors:login')

   if form.is_valid():
      is_authenticated = authenticate(
         username = form.cleaned_data.get('username', ''),
         password = form.cleaned_data.get('password', ''),
      )

      if is_authenticated is not None:
         messages.success(request, 'Your are logged in.')
         login (is_authenticated)
         return redirect(login_url)
      messages.error(request, 'Invalid credentials')
      return redirect(login_url)
   
   messages.error(request, 'Invalid username or password')
   return redirect(reverse('authors:dashboard'))

@login_required(login_url='authors:login', redirect_field_name='next')
def logout_view(request):
    if not request.POST:
        return redirect(reverse('authors:login'))

    if request.POST.get('username') != request.user.username:
        return redirect(reverse('authors:login'))

    logout(request)
    return redirect(reverse('authors:login'))


@login_required(login_url='authors:login', redirect_field_name='next')
def dashboard(request):
   recipes = Recipe.objects.filter(
      is_published=False,
      author=request.user
   )
   return render(request, 'authors/pages/dashboard.html', context={
      'recipes': recipes,
   })

authors/views/all.py
from django.shortcuts import render, redirect
from ..forms import RegisterForm, LoginForm
from django.http import Http404
from django.contrib import messages
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from recipes.models import Recipe

def register_view(request):
   register_form_data = request.session.get('register_form_data', None)
   form = RegisterForm(register_form_data)
   return render(request, 'authors/pages/register_view.html', {
      'form': form,
   })

def register_create(request):
   if not request.POST:
      raise Http404()
   
   POST = request.POST
   request.session['register_form_data'] = POST
   form = RegisterForm(POST)

   if form.is_valid():
      user = form.save(commit=False)
      user.set_password(user.password)
      user.save()
      messages.success(request, 'Your user is created, please log in.')
      del(request.session['register_form_data'])
      return redirect(reverse('authors:login'))
   
   return redirect('authors:register')

def login_view(request):
   form = LoginForm()
   return render(request, 'authors/pages/login.html', {
      'form': form,
      'form_action': reverse('authors:login_create')
   })

def login_create(request):
   if not request.POST:
      raise Http404()
   
   form = LoginForm(request.POST)
   login_url = reverse('authors:login')

   if form.is_valid():
      is_authenticated = authenticate(
         username = form.cleaned_data.get('username', ''),
         password = form.cleaned_data.get('password', ''),
      )

      if is_authenticated is not None:
         messages.success(request, 'Your are logged in.')
         login (is_authenticated)
         return redirect(login_url)
      messages.error(request, 'Invalid credentials')
      return redirect(login_url)
   
   messages.error(request, 'Invalid username or password')
   return redirect(reverse('authors:dashboard'))

@login_required(login_url='authors:login', redirect_field_name='next')
def logout_view(request):
    if not request.POST:
        return redirect(reverse('authors:login'))

    if request.POST.get('username') != request.user.username:
        return redirect(reverse('authors:login'))

    logout(request)
    return redirect(reverse('authors:login'))


@login_required(login_url='authors:login', redirect_field_name='next')
def dashboard(request):
   recipes = Recipe.objects.filter(
      is_published=False,
      author=request.user
   )
   return render(request, 'authors/pages/dashboard.html', context={
      'recipes': recipes,
   })

authors/templates/authors/pages/dashboard.html
{% extends "global/base.html" %}
{% block title %}Register |{% endblock title %}
{% block content %}
    <div class="main-content center container">
        <h2>Dashboard</h2>
    </div>
    
    {% include "recipes/partials/message.html" %}

    
{% endblock content %}

authors/templates/authors/pages/dashboard_recipe.html
{% extends "global/base.html" %}
{% block title %}Dashboard recipe |{% endblock title %}
{% block content %}
    <div class="main-content center container">
        <h2>Dashboard Recipe</h2>
        <div class="authors-dashboard-container">
            
          </div>
    </div>
    
    {% include "recipes/partials/message.html" %}

    
{% endblock content %}

authors/templates/authors/pages/login.html
{% extends "global/base.html" %}
{% block title %}Login |{% endblock title %}
{% block content %}
    <div class="main-content center container">
        <h2>Login</h2>
    </div>
    
    {% include "recipes/partials/message.html" %}

    <div class="main-content container">
        <form action="{% url "authors:login" %}" method="POST">
            {% csrf_token %}
            <div class="form-content form-content-grid">
                {% for field in form %}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field }}
                    {% if field.help_text %}
                        <p class="help-text">{{ field.help_text }}</p>
                    {% endif %}
                    {{ field.errors }}
                </div>
                {% endfor %}
        </div>
        <div class="form-content form-content-grid">
            <div class="form-group">
                <button type="submit">Send</button>
            </div>
        </div>
        {% if form.errors %}
             <div class="form-content form-content-grid">
                <div class="form-group">
                    <div class="message message-error">
                        Por favor corrija os erros
                    </div>
                </div>
            </div>
        {% endif %}
        {% if request.user.is_authenticated %}
            <p>
                your are logged in with {{ request.user.username }}.
                
                <form action="{% url "authors:logout" %}" method="POST">
                    {% csrf_token %} 
                    <input type="hidden" name="username" value="{{ request.user.username }}">
                    <button class="plaintext-button" type="submit">click here</button>
                </form> to logout
            </p>
        {% endif %}
        </form>
    </div>
{% endblock content %}

authors/templates/authors/pages/register_view.html
{% extends "global/base.html" %}
{% block title %}Register |{% endblock title %}
{% block content %}
    <div class="main-content center container">
        <h2>Register</h2>
    </div>
    
    {% include "recipes/partials/message.html" %}

    <div class="main-content container">
        <form action="{% url "authors:create" %}" method="POST">
            {% csrf_token %}
            <div class="form-content form-content-grid">
                {% for field in form %}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field }}
                    {% if field.help_text %}
                        <p class="help-text">{{ field.help_text }}</p>
                    {% endif %}
                    {{ field.errors }}
                </div>
                {% endfor %}
        </div>
        <div class="form-content form-content-grid">
            <div class="form-group">
                <button type="submit">Send</button>
            </div>
        </div>
        {% if form.errors %}
             <div class="form-content form-content-grid">
                <div class="form-group">
                    <div class="message message-error">
                        Por favor corrija os erros
                    </div>
                </div>
            </div>
        {% endif %}
        </form>
    </div>
{% endblock content %}